import os
import pickle
import numpy as np
import tensorflow as tf
from music21 import instrument, note, stream, chord

# Import our custom network builder
from model import create_network 

def generate_music():
    """ 
    Generate a new music sequence from the trained neural network.
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))
    notes_file = os.path.join(base_dir, "notes.pkl")
    model_path = os.path.join(base_dir, "music_model.h5")
    
    # Gracefully handle missing files
    if not os.path.exists(notes_file):
        print(f"Error: {notes_file} not found.")
        print("Please run preprocess.py first to extract notes.")
        return
        
    if not os.path.exists(model_path):
        print(f"Error: {model_path} not found.")
        print("Please run train.py first to train the model.")
        return
        
    print(f"Loading notes from {notes_file}...")
    with open(notes_file, 'rb') as filepath:
        notes = pickle.load(filepath)
        
    pitchnames = sorted(set(item for item in notes))
    n_vocab = len(set(notes))
    
    # Create the model architecture
    print("Rebuilding model architecture...")
    model = create_network(n_vocab)
    
    # Load the weights from the trained model
    print(f"Loading weights from {model_path}...")
    model.load_weights(model_path)
    
    # Prepare mapping functions
    note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
    int_to_note = dict((number, note) for number, note in enumerate(pitchnames))
    
    sequence_length = 100
    network_input = []
    
    # Prepare inputs for starting sequence selection
    for i in range(0, len(notes) - sequence_length, 1):
        sequence_in = notes[i:i + sequence_length]
        network_input.append([note_to_int[char] for char in sequence_in])
        
    if not network_input:
        print("Error: Not enough notes in notes.pkl to create a sequence of length 100.")
        print("Please provide more MIDI files for preprocessing.")
        return
        
    # Pick a random starting sequence from the training data
    start_index = np.random.randint(0, len(network_input)-1)
    pattern = network_input[start_index]
    
    print("Random starting sequence selected.")
    print("Generating 500 new notes by predicting one note at a time...")
    
    prediction_output = []
    
    # Generate 500 notes
    for note_index in range(500):
        # Format the input sequence for the model
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))
        prediction_input = prediction_input / float(n_vocab)
        
        # Predict the next note
        prediction = model.predict(prediction_input, verbose=0)
        
        # Get the index with highest probability
        index = np.argmax(prediction)
        
        # Map predicted integer back to note/chord string
        result = int_to_note[index]
        prediction_output.append(result)
        
        # Feed the output back as input by sliding the window
        pattern.append(index)
        pattern = pattern[1:len(pattern)]
        
        if (note_index + 1) % 50 == 0:
            print(f"Generated {note_index + 1}/500 notes...")
            
    print("Generation complete. Converting sequence to MIDI file...")
    create_midi(prediction_output, base_dir)

def create_midi(prediction_output, base_dir):
    """ 
    Convert the output from the prediction back to a playable MIDI file.
    """
    offset = 0
    output_notes = []
    
    # Create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # If the pattern contains a dot (.) or is numeric -> treat as a Chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
            
        # Otherwise -> treat as a Note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)
            
        # Set each note's offset to increment by 0.5 so notes don't stack
        offset += 0.5
        
    # Build a music21 Stream
    midi_stream = stream.Stream(output_notes)
    
    # Write the output Stream as a MIDI file
    output_file = os.path.join(base_dir, "output.mid")
    midi_stream.write('midi', fp=output_file)
    
    print(f"Successfully saved generated music to {output_file}")

if __name__ == '__main__':
    generate_music()
